# Load test configuration variables
# Generated by Terraform - DO NOT EDIT MANUALLY

# Resource information
$RESOURCE_GROUP = "nabk-lt-rg"
$LOAD_TEST_NAME = "nabk-lt"
$TEST_NAME = "postgresql-load-test"
$TEST_DESCRIPTION = "Performance test of replication under load: 60 seconds"
$TARGET_URL = "https://example.com"
$ENGINE_INSTANCES = 4

# PostgreSQL server information
$PRIMARY_SERVER_NAME = "nabkltpg"
$PRIMARY_SERVER_FQDN = "nabkltpg.postgres.database.azure.com"
$REPLICA_SERVER_NAME = "nabkltpgrepl"
$REPLICA_SERVER_FQDN = "nabkltpgrepl.postgres.database.azure.com"
$DATABASE_NAME = "test"

# Test parameters
$MAIN_THREADS = 10
$MAIN_LOOPS = 100
$MAIN_DATABASE = "jdbc:nabkltpg.postgres.database.azure.com:5432/test"
$REPLICA_THREADS = 40
$REPLICA_LOOPS = 400
$REPLICA_DATABASE = "jdbc:nabkltpgrepl.postgres.database.azure.com:5432/test"
$MAIN_WRITES_PER_MINUTE = 120
$REPLICA_READS_PER_MINUTE = 480

# Credentials - as Key Vault references with full secret identifiers
$POSTGRES_ADMIN_USERNAME_SECRET = "https://nabkltkv.vault.azure.net/secrets/postgres-username/1383e1863ca14ad0b8e6eb4a32de1c59"
$POSTGRES_ADMIN_PASSWORD_SECRET = "https://nabkltkv.vault.azure.net/secrets/postgres-password/4b5b6052ca2741f5a1dde43169f68863"

# The complete secret URLs for direct reference (these include version GUIDs)
$POSTGRES_USERNAME_SECRET_URL = "https://nabkltkv.vault.azure.net/secrets/postgres-username/1383e1863ca14ad0b8e6eb4a32de1c59"
$POSTGRES_PASSWORD_SECRET_URL = "https://nabkltkv.vault.azure.net/secrets/postgres-password/4b5b6052ca2741f5a1dde43169f68863"

# Direct values (for script use - not recommended for secrets in load tests)
$POSTGRES_ADMIN_USERNAME = "pgadmin"
$POSTGRES_ADMIN_PASSWORD = "Password123!"

# Identity information - multiple formats for different contexts
$USER_ASSIGNED_IDENTITY_NAME = "nabk-lt-uai"
# Full resource ID (ARM format)
$USER_ASSIGNED_IDENTITY_ID = "/subscriptions/b7d84abb-da82-415d-801b-d0b26c0f9548/resourceGroups/nabk-lt-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nabk-lt-uai"
# Client ID of the managed identity (needed for some applications)
$USER_ASSIGNED_IDENTITY_CLIENT_ID = "4dd7fce9-18f4-432b-a755-666d0a64fb8f"
# Principal ID of the managed identity (object ID in AAD)
$USER_ASSIGNED_IDENTITY_PRINCIPAL_ID = "ea4655c6-b9f4-4723-af8f-53f8d289bded"
# Shorter format sometimes used in Azure Load Test
$USER_ASSIGNED_IDENTITY_RESOURCE_NAME = "/subscriptions/b7d84abb-da82-415d-801b-d0b26c0f9548/resourcegroups/nabk-lt-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/nabk-lt-uai"

# Primary resource IDs for monitoring - these will need the subscription ID added by the script
$PRIMARY_DB_RESOURCE = "Microsoft.DBforPostgreSQL/flexibleServers/nabkltpg"
$REPLICA_DB_RESOURCE = "Microsoft.DBforPostgreSQL/flexibleServers/nabkltpgrepl"
$PRIMARY_SERVER_ID = "/subscriptions/b7d84abb-da82-415d-801b-d0b26c0f9548/resourceGroups/nabk-lt-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/nabkltpg"
$REPLICA_SERVER_ID = "/subscriptions/b7d84abb-da82-415d-801b-d0b26c0f9548/resourceGroups/nabk-lt-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/nabkltpgrepl"

# Other resources
$KEY_VAULT_NAME = "nabkltkv"

# Test criteria
$ERROR_PERCENTAGE = 90
$TIME_WINDOW = 60

# File paths
$SCRIPT_PATH = "../load_test_artifacts/jmeter_script.jmx"
$JAR_PATH = "../load_test_artifacts/postgresql-42.7.5.jar"

# Config file path
$CONFIG_JSON_PATH = "./load_test_config.json"

# Note: To use these variables in your setup script, dot-source this file:
# . ./load_test_variables.ps1